# Generated by Django 5.2.4 on 2025-10-12 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_coustomuser_bio'),
    ]

    operations = [
    ]
