# Generated by Django 5.2.4 on 2025-10-12 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coustomuser',
            name='bio',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
